project:
  type: website

website:
  title: "CogPsych Reserve"
  navbar:
    right:
      - text: "About"
        href: https://www.s-hochman.com
      - icon: github
        href: https://github.com/ShacharHochman/Cog.Psych.Reserve
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/hochmanshachar.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/in/shachar-hochman-phd
      - icon: twitter
        href: https://x.com/HochmanShachar

format:
  html:
    theme: cosmo
    css:
      - styles.css
      
execute:
  freeze: auto
