project:
  type: website

website:
  title: "CogPsych Reserve"
  navbar:
    right:
      - text: "About"
        href: https://www.s-hochman.com
      - icon: github
        href: https://github.com/ShacharHochman/Cog.Psych.Reserve
      - icon: linkedin
        href: https://www.linkedin.com/in/shachar-hochman-phd
      - icon: twitter
        href: https://x.com/HochmanShachar

format:
  html:
    theme: cosmo
    css:
      - styles.css
      - _includes/comments.css
    filters:
      - include-after-body.lua
    include-after-body: _includes/comments.html
    variables:
      staticman_url:   staticman_url: https://cog-psych-res-app-b43552a94c8b.herokuapp.com/v3/entry/github/ShacharHochman/Cog.Psych.Reserve/main

execute:
  freeze: auto
