[build]
  publish = "_site"
  functions = "netlify/functions"
  command = "quarto render"

[[plugins]]
  package = "@quarto/netlify-plugin-quarto"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST"
    Access-Control-Allow-Headers = "Content-Type"
